Feature/events
STA-Development/Evaluation-App pull request #10
Opened 2022-04-06 18:45 UTC by yavetisyan

2022-04-25 18:01 UTC, ArthurO2002 requested changes

2022-04-25 18:01 UTC, ArthurO2002 commented on src/pages/events/eventsInfo/ongoingEvent/eventTable/Report.tsx
> +export default Report;
fix

2022-04-25 18:01 UTC, ArthurO2002 commented on src/pages/events/eventsInfo/ongoingEvent/eventTable/TableContent.tsx
> +
This same function is in 3 PR s

2022-04-25 18:01 UTC, ArthurO2002 commented on src/pages/events/eventsInfo/ongoingEvent/eventTable/TableHeader.tsx
> +    id: uuidv4(),
tbhis too

2022-04-25 18:01 UTC, ArthurO2002 commented on src/pages/events/eventsInfo/ongoingEvent/eventTable/TableHeader.tsx
> +  const classes = useEventsStyle()
fix interfavce name

2022-04-26 05:31 UTC, yavetisyan commented on src/assets/images/auth/ChangePassword.tsx
> +export default ChangePassword;
Done

2022-04-27 15:43 UTC, ArthurO2002 commented on src/pages/sidebar/Sidebar.tsx
>              <Button variant="contained" size="large" className={globalClasses.button}>
text-decoration-none

2022-04-27 15:55 UTC, yavetisyan commented on src/pages/sidebar/Sidebar.tsx
>              <Button variant="contained" size="large" className={globalClasses.button}>
Done

2022-04-27 18:01 UTC, ArthurO2002 commented on src/assets/style/events/events.scss
> +  &-date {
this too

2022-04-27 18:09 UTC, ArthurO2002 approved these changes

2022-04-27 18:10 UTC, merged