Feature/submissions
STA-Development/Evaluation-App pull request #13
Opened 2022-04-18 14:04 UTC by yavetisyan

2022-04-25 17:54 UTC, ArthurO2002 requested changes

2022-04-25 17:54 UTC, ArthurO2002 commented on src/pages/dashboard/SliderPerformers.tsx
> +          <Box className="slider__box" key={item.id}>
same issue

2022-04-25 17:54 UTC, ArthurO2002 commented on src/pages/events/RootEvents.tsx
> +const a11yProps = (index: number) => ({
change function name

2022-04-25 17:54 UTC, ArthurO2002 commented on src/pages/events/eventsInfo/ongoingEvent/eventTable/TableContent.tsx
> +export type Order = 'asc' | 'desc'
move to types file

2022-04-25 17:54 UTC, ArthurO2002 commented on src/pages/events/eventsInfo/ongoingEvent/eventTable/TableContent.tsx
> +  }
move to utils

2022-04-25 17:54 UTC, ArthurO2002 commented on src/pages/events/eventsInfo/submission/Submissions.tsx
> +}
move to types

2022-04-25 17:54 UTC, ArthurO2002 commented on src/pages/sidebar/Sidebar.tsx
> +          <NavLink className="text__decoration_none" to="/">
issue with classes

2022-04-25 18:53 UTC, yavetisyan commented on src/pages/events/RootEvents.tsx
> +const a11yProps = (index: number) => ({
Done

2022-04-25 18:53 UTC, yavetisyan commented on src/pages/events/eventsInfo/ongoingEvent/eventTable/TableContent.tsx
> +export type Order = 'asc' | 'desc'
Done

2022-04-26 16:15 UTC, ArthurO2002 requested changes

2022-04-26 16:15 UTC, ArthurO2002 commented on src/assets/style/submissions/submissions.scss
> +  margin: 0 20px;
use variables

2022-04-26 16:15 UTC, ArthurO2002 commented on src/pages/dashboard/EmptyDashboard.tsx
>            <Button variant="contained">CREATE EVENT</Button>
not fixed

2022-04-26 16:15 UTC, ArthurO2002 commented on src/pages/events/eventsInfo/submission/submissionQuarterlyData/submissionNotFinished.ts
> +export default submissionNotFinished
what is the point of this file, if it's used in multiple places then use enum

2022-04-27 07:47 UTC, yavetisyan commented on src/types/types.ts
> +}
Done

2022-04-27 15:52 UTC, merged